export default {
  // common
  SET_BACKGROUND_CALLBACK: 'SET_BACKGROUND_CALLBACK',
  SET_DAPP_OPTIONS: 'SET_DAPP_OPTIONS',
  // account
  SET_SELECTED_ACCOUNT: 'SET_SELECTED_ACCOUNT',
  SET_LIST_ACCOUNTS: 'SET_LIST_ACCOUNTS',
  // network
  SET_SELECTED_NETWORK: 'SET_SELECTED_NETWORK',
  SET_LIST_NETWORKS: 'SET_LIST_NETWORKS',
  // token
  SET_SELECTED_TOKEN: 'SET_SELECTED_TOKEN'
}
